# Generated by Django 5.2.4 on 2025-08-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to=''),
        ),
    ]
