# Generated by Django 5.2.4 on 2025-08-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default_cover.png', upload_to=''),
        ),
    ]
